'use strict';

/**
 * BeHistorical Foundations Unit Examination, Version 3.
 *
 * The single source of truth for the exam. scripts/build-exam.js renders the
 * Canvas QTI package from this file and nothing else, so the questions are
 * edited here and never in the generated XML.
 *
 * ── Why version 3 exists ─────────────────────────────────────────────────────
 *
 * Version 2 was generated by a language model, read well, and was rated highly
 * by a five-persona review. All forty of its answer keys were historically
 * correct. It was still unusable, and the reasons are worth keeping written
 * down because none of them is visible to a reader:
 *
 *   1. The key was strictly the longest option in 38 of 40 items. A student who
 *      knew no history and always picked the longest option scored 95%.
 *   2. Absolutist words appeared in 22% of distractors and 2% of keys, so
 *      "cross off whatever sounds too strong" was a second free signal.
 *   3. Three items told students to read a Southern Song map. The image was
 *      instructional-maps/foundations-5.svg, which is the six AP regions map.
 *      It shows no Yangtze, no Lin'an and no Quanzhou. The alt text describing
 *      a Song map had been written to match a plausible filename.
 *   4. Eight items asked which statement "best demonstrates contextualization",
 *      or causation, or comparison. That tests whether a student recognizes a
 *      vocabulary word, and combined with cue 1 those eight were free.
 *   5. Christianity never appeared. Islam, Hinduism and Daoism appeared only as
 *      wrong answers. The Mediterranean sea lanes were never a correct answer.
 *      Every one of those sits inside a stated Foundations learning target.
 *   6. Twelve items hotlinked images, two of them to commons.wikimedia.org,
 *      which returned HTTP 429 under test. An exam cannot depend on a third
 *      party being reachable during the exam.
 *   7. One item referred to "the interpretation in Question 25", which points
 *      at nothing as soon as Canvas shuffles the order.
 *
 * scripts/check-exam-cues.js is the gate on 1, 2, 5, 6 and 7. It runs in the
 * offline suite, and it fails on a V2-shaped exam. What it cannot check is
 * whether a key is historically right, which stays a teacher's judgement.
 *
 * ── How this version is built ────────────────────────────────────────────────
 *
 * Every item belongs to a stimulus set, because that is the shape of the real
 * AP World multiple-choice section: a source, then questions about it. V2 left
 * 28 of 40 items with no stimulus at all and carried no text sources whatever.
 *
 * Every image is a repository file that students already load daily from the
 * course site, and every one has been checked against what it actually depicts.
 * The captions in the Foundations data files are the reference for that.
 *
 * The passages are written for this examination and are labelled as such in
 * `provenance`. Nothing here is attributed to a historian who did not write it,
 * and no quotation, statistic or date has been invented. Where a real excerpt
 * would teach better, swap one in and keep the label honest.
 *
 * The AP skills are assessed by requiring the skill on real content rather than
 * by asking students to identify its name. `skill` records which one an item
 * leans on so the teacher can read coverage, and it is never the answer.
 */

const IMG = {
  buddhism: {
    src: 'assets/images/maps/foundations-2/buddhism-spread-asia.webp',
    alt: 'Map of the origin and spread of Buddhism across Asia. Colored arrows separate three traditions: Theravada from the 3rd century BCE, Mahayana from the 1st century BCE or CE, and Vajrayana from the 7th century CE. Dates mark where Buddhism became established.',
    credit: 'The Origin and Spread of Buddhism Across Asia, World History Encyclopedia (worldhistory.org).'
  },
  persia: {
    src: 'assets/images/maps/foundations-3/persian-empires.jpg',
    alt: 'Map layering three Persian empires on one frame: the Achaemenid Empire of about 500 BCE, the Sassanid Empire of 621 CE, and the Safavid Empire of the 16th century. Place names on the map are modern countries.',
    credit: 'Used in Foundations 3, States, Power and Social Organization.'
  },
  monsoon: {
    src: 'assets/images/maps/foundations-4/indian-ocean-monsoon-trade.jpg',
    alt: 'Map of Indian Ocean trade routes and monsoon winds. One set of arrows runs April to September toward India, Southeast Asia and China. A second set runs November to February back toward Arabia and East Africa. Ports marked include Kilwa, Aden, Calicut, Melaka and Quanzhou.',
    credit: 'Used in Foundations 4, Trade Networks.'
  },
  regions: {
    src: 'assets/images/instructional-maps/foundations-5.svg',
    alt: 'Instructional map of the six AP World regions at c. 1200: East Asia (Song China, Korea, Japan); South and Southeast Asia (Delhi, Khmer, Srivijaya); Dar al-Islam across Southwest Asia and North Africa; Africa (Mali, Great Zimbabwe, the Swahili coast); Europe as fragmented feudal states; and the Americas (Inca, Mexica, Mississippian).',
    credit: 'BeHistorical instructional map, Foundations 5.'
  },
  rome: {
    src: 'assets/images/maps/foundations-3/roman-empire-height.jpg',
    alt: 'Map showing two stages of Roman expansion. A small red area marks the Roman Republic of 264 BCE, confined to Italy. A much larger yellow area marks the empire at its greatest extent in 117 CE, wrapping around the whole Mediterranean.',
    credit: 'Used in Foundations 3, States, Power and Social Organization.'
  }
};

const WRITTEN_FOR_EXAM =
  'This passage was written for this examination. It summarizes material covered in the Foundations readings and is not a quotation from a historical source.';

module.exports = {
  id: 'behistorical_foundations_v3',
  title: 'BeHistorical AP World History, Foundations Unit Examination, Version 3',
  description:
    'Forty multiple-choice questions in eleven source sets, one point each. Every item is attached to a map or a passage. Covers Foundations 1 through 5.',
  pointsPerItem: 1,

  /* Minimum items per Foundations day, checked by scripts/check-exam-cues.js.
   * These are floors rather than targets, so adding an item never fails the
   * gate and quietly dropping a day's coverage does. */
  coverage: { F1: 6, F2: 7, F3: 8, F4: 7, F5: 7 },

  /* Terms that must reach a student as something true, in a correct answer or
   * in the stem of the item that carries it. Every entry below was absent from
   * V2's keys, or present only as a wrong answer to cross off. */
  requiredInKeys: [
    'Christian', 'Islam', 'Hindu', 'Daoism', 'Confucian', 'Buddhis',
    'Mediterranean', 'Sahara', 'monsoon', 'Silk Road',
    'Mali', 'Dar al-Islam', 'Americas',
    'satrap', 'citizenship', 'surplus', 'Quanzhou', 'Kilwa'
  ],

  sets: [
    // ── SET A ────────────────────────────────────────────────────────────────
    {
      id: 'A',
      title: 'The Spread of Buddhism Across Asia',
      instruction: 'Use the map to answer the questions in this set.',
      image: IMG.buddhism,
      items: [
        {
          id: 'q001', target: 'F2', skill: 'causation',
          stem: 'The map shows Buddhism established in the Silk Road oasis towns of Kashgar, Khotan, Kucha and Dunhuang before it is established in China. What does that sequence best indicate about how Buddhism traveled?',
          choices: {
            A: 'It moved along established commercial routes, so towns that served merchants received it before China did.',
            B: 'It moved ahead of merchants along military roads, so garrison towns received it before the Chinese interior.',
            C: 'It moved outward from Chinese monasteries, so the oasis towns were supplied by missions sent from Chang’an.',
            D: 'It moved with pilgrims returning from China, so the oasis towns kept teachings that China had since dropped.'
          },
          key: 'A',
          why: {
            A: 'Correct. The oasis towns were commercial waypoints first. Buddhism reached them early because it moved with the people and institutions that used the route.',
            B: 'The route was commercial before it was military, and the map shows no army carrying the tradition east.',
            C: 'This reverses the direction. The map’s arrows run toward China, not outward from it.',
            D: 'Pilgrims did travel back west, but that is a later movement and does not explain why the oases are dated earlier.'
          }
        },
        {
          id: 'q002', target: 'F2', skill: 'comparison',
          stem: 'The map traces Theravada, Mahayana and Vajrayana along different routes and from different centuries. Which conclusion does that pattern best support?',
          choices: {
            A: 'Each region received the same tradition, and the colors record the order in which it arrived.',
            B: 'A belief system can take distinct forms as separate networks carry it into different regions.',
            C: 'A tradition divides once a state adopts it, so the colors track episodes of royal patronage.',
            D: 'A tradition’s form followed climate, so the colors match the environments each route crossed.'
          },
          key: 'B',
          why: {
            A: 'The three colors are three traditions, not three arrival dates for one tradition.',
            B: 'Correct. Different routes, different centuries and different receiving societies produced Theravada, Mahayana and Vajrayana as distinct forms.',
            C: 'Patronage mattered a great deal, but the map separates the colors by route and date rather than by ruler.',
            D: 'Vajrayana and Mahayana both crossed varied environments. Climate does not sort the colors.'
          }
        },
        {
          id: 'q003', target: 'F2', skill: 'continuity and change',
          stem: 'Mahayana Buddhism is marked in China around the first century CE, in Korea around the fourth, and in Japan around the sixth. What does that spacing best show?',
          choices: {
            A: 'Diffusion continued across centuries through connections that already linked those regions.',
            B: 'Diffusion stalled wherever a strong state existed, which held it back in Korea and Japan.',
            C: 'Diffusion depended on conquest, so each date marks the arrival of a Buddhist army.',
            D: 'Diffusion ran fastest by sea, so the dates record new maritime routes opening east.'
          },
          key: 'A',
          why: {
            A: 'Correct. Five centuries separate the first date from the last, and the tradition moved along ties that already ran between China, Korea and Japan.',
            B: 'Korea and Japan both had organized states, and both adopted the tradition rather than blocking it.',
            C: 'No Buddhist army is involved in this diffusion, which is one of the points the map is used to make.',
            D: 'The Mahayana route to China on this map is the overland one through the oases.'
          }
        },
        {
          id: 'q004', target: 'F2', skill: 'causation',
          stem: 'Short arrows fan out across South Asia in the third century BCE, the century in which Ashoka funded monasteries and sent out missions. Which mechanism of spread does that pattern best illustrate?',
          choices: {
            A: 'Merchants carrying a tradition along the trade routes into neighboring commercial markets.',
            B: 'Monks migrating away from persecution toward regions holding no established authority.',
            C: 'Rulers spending state resources on a tradition and extending it inside their own territory.',
            D: 'Farmers taking up a tradition that was believed to protect harvests in irrigated valleys.'
          },
          key: 'C',
          why: {
            A: 'Merchants carried Buddhism a long way, but these arrows are short and internal, which is the signature of patronage rather than trade.',
            B: 'The arrows spread from a center of power outward, which is not the shape of flight from persecution.',
            C: 'Correct. Royal patronage is a distinct mechanism, and it is the one that fits a burst of short-range expansion in Ashoka’s century.',
            D: 'The map records where the tradition became established, not agricultural practice.'
          }
        }
      ]
    },

    // ── SET B ────────────────────────────────────────────────────────────────
    {
      id: 'B',
      title: 'The Persian Empires',
      instruction: 'Use the map to answer the questions in this set. Foundations 3 concerns the Achaemenid layer, the empire of about 500 BCE.',
      image: IMG.persia,
      items: [
        {
          id: 'q005', target: 'F3', skill: 'causation',
          stem: 'The Achaemenid layer stretches from the Aegean to the Indus. Which governing problem does that extent most directly create for a ruler at Persepolis?',
          choices: {
            A: 'Gathering information and enforcing decisions across distances a messenger needs weeks to cross.',
            B: 'Growing enough grain inside the imperial capital to supply the provinces that surrounded it.',
            C: 'Finding a single written script able to record every language spoken across the territory.',
            D: 'Persuading neighboring empires to recognize the ruler’s claim to authority over the region.'
          },
          key: 'A',
          why: {
            A: 'Correct. Distance is the governing problem an empire of this size hands its ruler, and every tool of Persian rule is an answer to it.',
            B: 'Capitals were supplied by their provinces, not the other way round.',
            C: 'Administrative scripts existed and were used. This is a practical detail rather than the central problem of scale.',
            D: 'Recognition abroad mattered less than control at home, which is what the map’s extent makes hard.'
          }
        },
        {
          id: 'q006', target: 'F3', skill: 'sourcing',
          stem: 'This map layers three Persian empires from widely separated eras and labels the territory with modern country names. What does that most limit about its use as evidence?',
          choices: {
            A: 'It shows how far each empire reached but not how any of them actually governed a province.',
            B: 'It shows the borders of the Achaemenid state but leaves out the empires that came after it.',
            C: 'It shows the physical relief accurately but places the major imperial capitals in wrong spots.',
            D: 'It shows the trade routes crossing the plateau but omits the goods that moved along them.'
          },
          key: 'A',
          why: {
            A: 'Correct. Extent is what a map of this kind carries well. Administration, tribute and local practice have to come from other evidence.',
            B: 'The later empires are exactly what the other two layers show.',
            C: 'The capitals are placed correctly. The modern country names are the caution, not the locations.',
            D: 'This map is not a trade map, so omitting goods is not a limitation on its own purpose.'
          }
        },
        {
          id: 'q007', target: 'F3', skill: 'causation',
          stem: 'Darius governed the territory in the Achaemenid layer through satraps. How did that arrangement answer the problem the map’s extent creates?',
          choices: {
            A: 'It removed local elites from office so that each province was staffed from Persepolis outward.',
            B: 'It set a royal governor over each province, leaving local practice while tribute and loyalty ran up.',
            C: 'It divided the empire among the king’s heirs, each ruling a province as an independent kingdom.',
            D: 'It garrisoned every province with the royal army, putting military command in place of civil rule.'
          },
          key: 'B',
          why: {
            A: 'Persian rule worked with local elites rather than clearing them out, which is why it was cheap enough to sustain.',
            B: 'Correct. Delegated regional authority under a royal appointee is how an empire governs further than its ruler can see.',
            C: 'Satrapies were appointments, not inheritances, and independence is the opposite of the intention.',
            D: 'Garrisons existed, but the administration was civil and the satrap was a governor.'
          }
        }
      ]
    },

    // ── SET C ────────────────────────────────────────────────────────────────
    {
      id: 'C',
      title: 'The Indian Ocean and the Monsoon',
      instruction: 'Use the map to answer the questions in this set.',
      image: IMG.monsoon,
      items: [
        {
          id: 'q008', target: 'F4', skill: 'causation',
          stem: 'One set of arrows on the map runs from April to September and a second set runs from November to February in the opposite direction. Why did that pattern matter so much to merchants?',
          choices: {
            A: 'It let them plan an outward voyage and a return voyage around winds they could count on.',
            B: 'It let them sail in whatever direction they chose at any point in the year without waiting.',
            C: 'It let them keep clear of coastal ports and cross open water between any two harbours.',
            D: 'It let them carry heavier cargo, because these winds were gentler than Mediterranean gales.'
          },
          key: 'A',
          why: {
            A: 'Correct. Predictability is the whole mechanism. A wind that reverses on schedule turns a one-way gamble into a planned round trip.',
            B: 'The reversal is seasonal, so waiting for the turn was exactly what merchants had to do.',
            C: 'Ports were where cargo, water and buyers were. The monsoon made the route work, not the ports unnecessary.',
            D: 'Monsoon winds are strong, and cargo capacity was set by the ships rather than by the weather.'
          }
        },
        {
          id: 'q009', target: 'F4', skill: 'causation',
          stem: 'The map traces a route running from Kilwa through Aden and Calicut to Melaka and Quanzhou. Historians call this relay trade. What does that term describe?',
          choices: {
            A: 'Goods passing between merchants who each specialized in one leg of the longer route.',
            B: 'Goods traveling under naval escort, each state guarding the leg inside its own waters.',
            C: 'Goods moving on a fixed timetable, with ships leaving every port on the same date.',
            D: 'Goods carried the entire distance by crews who repaired their vessels at each port.'
          },
          key: 'A',
          why: {
            A: 'Correct. No single ship ran Kilwa to Quanzhou. The route worked because it was a chain of specialists, each with local knowledge.',
            B: 'No state controlled the whole ocean, which is part of why the relay structure existed.',
            C: 'Departures followed the monsoon, and the monsoon does not arrive on the same date at every port.',
            D: 'This is the misconception the term relay is meant to correct.'
          }
        },
        {
          id: 'q010', target: 'F4', skill: 'causation',
          stem: 'A merchant who sailed east in June could not sail home until the winds reversed months later. Which effect of that delay did the most to change the port cities themselves?',
          choices: {
            A: 'Merchants stayed a whole season, and resident foreign communities grew up in the ports.',
            B: 'Merchants left the route entirely, and the ports shrank back into fishing settlements.',
            C: 'Merchants demanded warships, and the ports were rebuilt around fortified naval bases.',
            D: 'Merchants raised their prices, and the ports lost their share of long-distance trade.'
          },
          key: 'A',
          why: {
            A: 'Correct. Waiting for a wind means living somewhere. That is how quarters of foreign merchants, and then intermarriage, language and religion, entered the port cities.',
            B: 'The route grew rather than emptied over this period.',
            C: 'Some ports were fortified, but the seasonal wait is not what drove it.',
            D: 'Prices moved, though that changes ledgers rather than the make-up of a city.'
          }
        },
        {
          id: 'q011', target: 'F4', skill: 'sourcing',
          stem: 'The map marks ports and wind directions but records nothing about cargo volumes. Which question can it therefore not answer on its own?',
          choices: {
            A: 'How much of any particular good actually moved along the route in a given season.',
            B: 'Which season carried ships eastward toward India, Southeast Asia and southern China.',
            C: 'Roughly whereabouts along the coast of East Africa the port of Kilwa was situated.',
            D: 'Which direction ships were traveling in the months between November and February.'
          },
          key: 'A',
          why: {
            A: 'Correct. Volume needs customs registers, wrecks or archaeology. A route map shows the shape of a network, not its scale.',
            B: 'The April to September arrows answer this directly.',
            C: 'Kilwa is marked on the map.',
            D: 'The November to February arrows answer this directly.'
          }
        }
      ]
    },

    // ── SET D ────────────────────────────────────────────────────────────────
    {
      id: 'D',
      title: 'The Six AP World Regions at c. 1200',
      instruction: 'Use the map and its key to answer the questions in this set.',
      image: IMG.regions,
      items: [
        {
          id: 'q012', target: 'F5', skill: 'comparison',
          stem: 'The key describes Europe at c. 1200 as fragmented feudal states, while East Asia is anchored by a single dynasty. Which comparison does that contrast best support?',
          choices: {
            A: 'Political power was organized at very different scales across regions at the same moment.',
            B: 'Political power was organized in much the same way everywhere once farming took hold.',
            C: 'Political power in Europe broke apart because it lacked rivers of the kind East Asia farmed.',
            D: 'Political power in East Asia rested on trade, while power in Europe rested on agriculture.'
          },
          key: 'A',
          why: {
            A: 'Correct. Reading the regions side by side at one date is what makes scale visible, and scale is the difference the key is pointing at.',
            B: 'The map exists to show that this is untrue.',
            C: 'Europe has large river systems. Fragmentation there has political causes rather than hydrological ones.',
            D: 'Both regions ran on agriculture, and both traded.'
          }
        },
        {
          id: 'q013', target: 'F5', skill: 'contextualization',
          stem: 'The map places the Inca, the Mexica and the Mississippian societies in the Americas. What is the most important thing to understand about their position at c. 1200?',
          choices: {
            A: 'They built complex societies while developing apart from regular Afro-Eurasian contact.',
            B: 'They built complex societies by adapting institutions carried east across the Pacific.',
            C: 'They stayed small farming settlements until Afro-Eurasian crops reached them by sea.',
            D: 'They traded on a regular basis with the states of West Africa across the Atlantic.'
          },
          key: 'A',
          why: {
            A: 'Correct. Complexity developed on both sides of the Atlantic. What separates them at c. 1200 is connection, not sophistication.',
            B: 'There is no evidence of sustained transpacific transfer of institutions in this period.',
            C: 'These were large, organized societies well before any Afro-Eurasian contact.',
            D: 'Regular Atlantic crossings do not begin in this period.'
          }
        },
        {
          id: 'q014', target: 'F5', skill: 'causation',
          stem: 'The key places Mali, Great Zimbabwe and the Swahili coast in Africa, and shows Dar al-Islam spanning Southwest Asia and North Africa just to their north. What does that arrangement help explain?',
          choices: {
            A: 'African states sat beside the routes that carried gold, salt and Islam across the region.',
            B: 'African states were governed from Southwest Asia by officials sent south every year.',
            C: 'African states grew up in isolation until European traders arrived along the coast.',
            D: 'African states shared a single language, which is why the map groups them together.'
          },
          key: 'A',
          why: {
            A: 'Correct. Position on a network is the point. Mali sat on the Saharan gold and salt routes and the Swahili coast sat on the Indian Ocean, and Islam moved along both.',
            B: 'Mali and the Swahili city-states governed themselves.',
            C: 'Both were connected to major networks centuries before Europeans reached the coast.',
            D: 'A region on this map is an analytic grouping, not a language group.'
          }
        },
        {
          id: 'q015', target: 'F5', skill: 'sourcing',
          stem: 'A note on the map states that these six regions are an analytic frame rather than natural divisions. What does that caution mean for a student using it?',
          choices: {
            A: 'The regions are a tool for comparison, and their boundaries reflect choices historians made.',
            B: 'The regions are inaccurate, so the map should be set aside in favor of political borders.',
            C: 'The regions are natural units, so the societies inside one shared a common government.',
            D: 'The regions are modern inventions, so they cannot describe any world before c. 1500.'
          },
          key: 'A',
          why: {
            A: 'Correct. A frame is useful and chosen at the same time. Knowing who drew the line is part of using it well.',
            B: 'Political borders at c. 1200 would make comparison across the world harder, not easier.',
            C: 'This is precisely what the note is warning against.',
            D: 'A category devised later can still describe an earlier world, so long as its limits are understood.'
          }
        }
      ]
    },

    // ── SET E ────────────────────────────────────────────────────────────────
    {
      id: 'E',
      title: 'The Roman Empire, 264 BCE and 117 CE',
      instruction: 'Use the map to answer the questions in this set.',
      image: IMG.rome,
      items: [
        {
          id: 'q016', target: 'F3', skill: 'continuity and change',
          stem: 'The map shows a small area in Italy marked 264 BCE and a far larger territory marked 117 CE. Reading those two together, what can a student say about Roman expansion?',
          choices: {
            A: 'It took close to four centuries, turning one regional power into a Mediterranean empire.',
            B: 'It happened in a single generation, once the Roman legions were reorganized for war.',
            C: 'It reached its greatest extent early, and the later date records territory already lost.',
            D: 'It stayed within Italy throughout, and the yellow marks lands allied rather than ruled.'
          },
          key: 'A',
          why: {
            A: 'Correct. The distance between the two dates is the historical content of this map. Expansion on this scale is a process, not an event.',
            B: 'Nearly four centuries separate the two areas shown.',
            C: 'The larger area carries the later date, so the sequence runs the other way.',
            D: 'The yellow area is the empire at its greatest extent, well beyond Italy.'
          }
        },
        {
          id: 'q017', target: 'F3', skill: 'causation',
          stem: 'At its height Rome held territory on every shore of the Mediterranean. How did that sea function for the empire?',
          choices: {
            A: 'As its main highway, carrying grain, soldiers and officials faster than any road could.',
            B: 'As its main barrier, forcing the empire to move everything overland around the coast.',
            C: 'As its main frontier, marking the limit past which Roman authority did not reach.',
            D: 'As its main market, supplying the fish and the salt that most provinces relied on.'
          },
          key: 'A',
          why: {
            A: 'Correct. Water transport was far cheaper and faster than road transport, so an empire wrapped around a sea is an empire with a highway down its middle.',
            B: 'Rome built excellent roads and still moved bulk goods by sea wherever it could.',
            C: 'The frontiers were on the Rhine, the Danube, the desert and in Britain, not in the middle of the empire.',
            D: 'Mediterranean fisheries mattered, though grain from Egypt and North Africa was the cargo that fed Rome.'
          }
        },
        {
          id: 'q018', target: 'F3', skill: 'causation',
          stem: 'Governing the territory shaded yellow meant ruling millions of people who were not Roman. Which practice did the most to bind them to the empire over time?',
          choices: {
            A: 'Extending a shared law and, gradually, citizenship, giving provincials a stake in Roman rule.',
            B: 'Settling Italian farmers across every province until provincials became a small minority.',
            C: 'Taxing the provinces so lightly that Roman rule cost less than local rule had cost before.',
            D: 'Obliging provincials to worship the Roman gods and to close their own local shrines.'
          },
          key: 'A',
          why: {
            A: 'Correct. Rome turned conquered people into Romans over generations. That is the mechanism, and it is what distinguishes Roman rule from simple occupation.',
            B: 'Colonies were founded, but provincials remained the great majority everywhere.',
            C: 'Provincial taxation was heavy, and it is what paid for the army.',
            D: 'Rome generally absorbed local gods rather than closing their shrines.'
          }
        }
      ]
    },

    // ── SET F ────────────────────────────────────────────────────────────────
    {
      id: 'F',
      title: 'Surplus and the First Cities',
      instruction: 'Read the passage, then answer the questions in this set.',
      provenance: WRITTEN_FOR_EXAM,
      passage:
        '<p>For most of human history people fed themselves by hunting and gathering, moving with the seasons and carrying little. In several river valleys, farming families began to bring in more grain than a household would eat in a year.</p>' +
        '<p>Stored grain is a claim on somebody else’s future labor. It can feed a potter, a soldier, a priest or a scribe, none of whom grows anything. Within a few generations, the settlements holding the largest stores were also the settlements with the most specialists, the sharpest differences in wealth, and the first officials whose work was to count what had been stored.</p>',
      items: [
        {
          id: 'q019', target: 'F1', skill: 'causation',
          stem: 'According to the passage, what makes stored grain historically significant?',
          choices: {
            A: 'It can support people who grow no food of their own.',
            B: 'It can be traded to distant settlements for finished goods.',
            C: 'It can be replanted to raise the yield of the following year.',
            D: 'It can be kept for far longer than hunted or gathered food.'
          },
          key: 'A',
          why: {
            A: 'Correct. A surplus is what pays for a person who does not farm, and every specialist in a city is one of those people.',
            B: 'Trade grew from surplus, but the passage puts specialists first.',
            C: 'Seed grain matters agriculturally. It is not what the passage argues made storage historically important.',
            D: 'Storage life is a property of grain. The passage is interested in what the store lets a society do.'
          }
        },
        {
          id: 'q020', target: 'F1', skill: 'causation',
          stem: 'The passage links storage to the appearance of officials. What causal connection does it describe?',
          choices: {
            A: 'A store had to be counted and controlled, which made a job for administrators.',
            B: 'Officials came first, and ordered farmers to grow more grain than they needed.',
            C: 'Officials were priests whose rituals were thought to protect the coming harvest.',
            D: 'A store drew raiders, so settlements appointed officers to guard the granary.'
          },
          key: 'A',
          why: {
            A: 'Correct. Record keeping is not decoration. Somebody has to know what is in the store, whose it is and who may draw on it, and that person is the first bureaucrat.',
            B: 'This reverses the sequence the passage gives.',
            C: 'Religious authority did grow alongside the state, though the passage ties officials to counting.',
            D: 'Defense mattered, but the passage names counting rather than guarding.'
          }
        },
        {
          id: 'q021', target: 'F1', skill: 'causation',
          stem: 'A farming settlement lasts for generations without developing specialists or officials. Which explanation fits the passage’s argument best?',
          choices: {
            A: 'Its harvests fed the households that grew them, leaving no dependable surplus to store.',
            B: 'Its farmers agreed among themselves that nobody there should specialize in a craft.',
            C: 'Its site had no river, so irrigation and therefore writing never became possible there.',
            D: 'Its people went on hunting as well as farming, which the passage treats as a barrier.'
          },
          key: 'A',
          why: {
            A: 'Correct. Farming is not the condition the passage identifies. A dependable surplus is, and plenty of farming societies never produced one.',
            B: 'The passage explains this structurally rather than by collective decision.',
            C: 'Writing followed the need to keep accounts, which follows the surplus rather than the river.',
            D: 'Mixed subsistence was common and the passage nowhere treats it as a barrier.'
          }
        },
        {
          id: 'q022', target: 'F1', skill: 'argumentation',
          stem: 'Which of the following is the passage’s argument, rather than a piece of evidence it reports?',
          choices: {
            A: 'A stored surplus was the condition that made specialists and officials possible.',
            B: 'People fed themselves by hunting and gathering for most of human history.',
            C: 'Farming families in several river valleys grew more grain than they consumed.',
            D: 'Settlements holding the largest grain stores also held the most specialists.'
          },
          key: 'A',
          why: {
            A: 'Correct. This is the causal claim the passage is making. The other three are the observations it makes the claim from.',
            B: 'This is background the passage reports.',
            C: 'This is an observation the argument is built on.',
            D: 'This is the correlation. The argument is the claim about why the two go together.'
          }
        }
      ]
    },

    // ── SET G ────────────────────────────────────────────────────────────────
    {
      id: 'G',
      title: 'Two Answers to One Landscape',
      instruction: 'Read the passage, then answer the questions in this set.',
      provenance: WRITTEN_FOR_EXAM,
      passage:
        '<p>Two societies can meet the same kind of landscape and answer it differently. The grasslands north of China carried herds rather than fields, and the people there built their lives around animals, movement, and a way of making war that depended on both. The floodplains to the south carried dense grain farming, and the people there built canals, granaries, and officials to run them.</p>' +
        '<p>Geography did not hand down orders. It set the terms of the problem. Each society chose how to answer it.</p>',
      items: [
        {
          id: 'q023', target: 'F1', skill: 'contextualization',
          stem: 'Which statement best expresses the passage’s view of what geography does?',
          choices: {
            A: 'It shapes the range of workable choices without settling which one gets taken.',
            B: 'It settles which political and religious institutions a society will develop.',
            C: 'It matters at the beginning of a society and stops mattering once states form.',
            D: 'It matters less than the decisions rulers take about taxation and about war.'
          },
          key: 'A',
          why: {
            A: 'Correct. Constraint and choice together. That is the distinction the last two sentences of the passage are drawing.',
            B: 'This is the determinism the passage explicitly rejects.',
            C: 'Nothing in the passage suggests geography switches off.',
            D: 'The passage ranks neither above the other. It describes how they interact.'
          }
        },
        {
          id: 'q024', target: 'F1', skill: 'causation',
          stem: 'Why did the grasslands north of China carry herding rather than intensive grain farming?',
          choices: {
            A: 'Grass grows where rainfall is too limited and too uncertain to carry a grain crop.',
            B: 'Grass drains the soil so quickly that grain planted there fails within one season.',
            C: 'Grasslands lie too far to the north for any of the grains domesticated in Asia.',
            D: 'Grasslands were held by herders, who kept farming communities from settling.'
          },
          key: 'A',
          why: {
            A: 'Correct. Rainfall is the constraint. Animals convert grass a person cannot eat into food a person can, which is what makes marginal land productive.',
            B: 'Grassland soils are frequently rich. Water, not fertility, is the limit.',
            C: 'Latitude alone does not rule out grain, and hardy grains grow well to the north.',
            D: 'This describes a political outcome rather than the environmental condition behind it.'
          }
        },
        {
          id: 'q025', target: 'F1', skill: 'causation',
          stem: 'The passage groups canals, granaries and officials together in one phrase. What connection does that grouping suggest?',
          choices: {
            A: 'Managing water and stored grain took coordination, and coordination grew into administration.',
            B: 'Building canals took quarried stone, which is why officials came to control the quarries.',
            C: 'Officials were required to settle the disputes that arose over ownership of the herds.',
            D: 'Granaries were built first, and canals followed once the officials had been appointed.'
          },
          key: 'A',
          why: {
            A: 'Correct. A canal serves many fields and a granary holds many households’ grain. Both need somebody with authority over more than one family.',
            B: 'Canals in these floodplains were largely earthworks.',
            C: 'Herds belong to the grassland half of the passage.',
            D: 'The passage sets no order between them, and the point is that they come together.'
          }
        }
      ]
    },

    // ── SET H ────────────────────────────────────────────────────────────────
    {
      id: 'H',
      title: 'Belief Systems as Institutions',
      instruction: 'Read the passage, then answer the questions in this set.',
      provenance: WRITTEN_FOR_EXAM,
      passage:
        '<p>A belief system becomes a force in history when it acquires institutions: buildings, income, staff, and a part in public life. A Buddhist monastery in a Silk Road oasis housed monks, held donated land, taught boys to read, and lodged merchants. A Christian monastery in Europe copied manuscripts, farmed its estates, and fed the poor. Schools of Islamic law trained the judges who settled disputes in market towns. Chinese governments recruited officials by examining them on Confucian texts.</p>' +
        '<p>In each case a set of ideas had become a set of institutions. Institutions leave records.</p>',
      items: [
        {
          id: 'q026', target: 'F2', skill: 'contextualization',
          stem: 'The passage describes a Christian monastery in Europe copying manuscripts, farming its estates and feeding the poor. What does that combination best show?',
          choices: {
            A: 'A religious house working as a landowner, a school and a welfare provider at once.',
            B: 'A religious house withdrawing from the world in order to concentrate on prayer.',
            C: 'A religious house depending on royal grants for nearly everything it consumed.',
            D: 'A religious house serving as the local court where disputes were finally settled.'
          },
          key: 'A',
          why: {
            A: 'Correct. Three functions a modern person would expect from three separate bodies, carried by one institution. That is what makes it a social institution rather than a private faith.',
            B: 'Withdrawal was part of the ideal, and the listed activities are all engagement with the world.',
            C: 'Monasteries held land and produced their own income, which is what made them durable.',
            D: 'The passage gives the judging role to schools of Islamic law, not to the monastery.'
          }
        },
        {
          id: 'q027', target: 'F2', skill: 'comparison',
          stem: 'Which example in the passage most clearly shows a belief system carrying out work a modern reader would expect a government to do?',
          choices: {
            A: 'Schools of Islamic law training the judges who settled disputes in market towns.',
            B: 'A Buddhist monastery lodging merchants passing through a Silk Road oasis town.',
            C: 'A Christian monastery copying manuscripts on the estates that it farmed itself.',
            D: 'A household keeping a dietary rule at home on the days its tradition sets out.'
          },
          key: 'A',
          why: {
            A: 'Correct. Deciding disputes with binding force is the core business of a legal system, and here a religious institution supplies it.',
            B: 'This is closer to commercial infrastructure than to government.',
            C: 'Copying and farming are economic and cultural work rather than governing.',
            D: 'This is personal observance, which is the thing an institution is being contrasted with.'
          }
        },
        {
          id: 'q028', target: 'F2', skill: 'contextualization',
          stem: 'In South Asia, ideas about dharma set out duties that differed according to a person’s place in the social order. What does that best show about Hinduism in this period?',
          choices: {
            A: 'It gave religious form to an existing hierarchy and organized social obligation through it.',
            B: 'It transferred political authority away from kings and settled it on priests instead.',
            C: 'It spread mainly by conquest, which is how its rules about social duty became binding.',
            D: 'It taught that duties were the same for everyone, whatever position a person held.'
          },
          key: 'A',
          why: {
            A: 'Correct. Duty that varies by social position is exactly how a belief system can organize a society without any state doing the organizing.',
            B: 'Kings and priests both held authority, in a relationship that varied by place and period.',
            C: 'Hinduism in this period spread through settlement, patronage and cultural influence.',
            D: 'Duties differing by position is the specific feature described.'
          }
        },
        {
          id: 'q029', target: 'F2', skill: 'causation',
          stem: 'Buddhism entering China met Daoism, an older tradition that valued spontaneity and harmony with nature, and Chan Buddhism grew out of that meeting. Which term describes what happened?',
          choices: {
            A: 'Syncretism, the blending that happens when traditions meet and adapt to each other.',
            B: 'Diffusion, the movement of a tradition outward from the region where it started.',
            C: 'Schism, the splitting of a tradition into rival branches over a point of doctrine.',
            D: 'Orthodoxy, the fixing of a tradition’s teaching by an authority able to enforce it.'
          },
          key: 'A',
          why: {
            A: 'Correct. Two traditions meet and something new comes out that belongs wholly to neither. Chan is the standard example.',
            B: 'Diffusion is how Buddhism got to China. It does not describe what happened once it arrived.',
            C: 'A schism is a split inside one tradition, and Chan came from contact between two.',
            D: 'Orthodoxy runs the other way, toward fixing a tradition rather than changing it.'
          }
        }
      ]
    },

    // ── SET I ────────────────────────────────────────────────────────────────
    {
      id: 'I',
      title: 'Four Networks and What Moved Along Them',
      instruction: 'Read the passage, then answer the questions in this set.',
      provenance: WRITTEN_FOR_EXAM,
      passage:
        '<p>Four networks carried Afro-Eurasian trade before c. 1200. The Silk Roads crossed deserts and mountains by camel and pack animal. The trans-Saharan caravans crossed sand that kills horses, and became practical at scale once the camel saddle let traders load heavy freight. The Indian Ocean lanes ran on the monsoon and on ships such as the dhow, rigged with a lateen sail that could make ground across the wind. The Mediterranean lanes tied Europe, North Africa and Southwest Asia into a single basin.</p>' +
        '<p>Along all four moved goods. Along all four also moved crops, techniques, beliefs, people and disease.</p>',
      items: [
        {
          id: 'q030', target: 'F4', skill: 'causation',
          stem: 'Why does the passage treat the camel saddle as important for trans-Saharan trade?',
          choices: {
            A: 'It let traders carry loads heavy enough to make the desert crossing worth making.',
            B: 'It let traders cross the desert without having to stop at the oases along the way.',
            C: 'It let traders use horses in place of camels, since horses moved faster over sand.',
            D: 'It let traders navigate by the stars, which made the crossing far less dangerous.'
          },
          key: 'A',
          why: {
            A: 'Correct. The Sahara could always be crossed. What the saddle changed was the economics: enough freight per animal to repay the journey.',
            B: 'Oases remained essential, since the animals and the people had to drink.',
            C: 'The passage says the Sahara kills horses, which is why the camel matters.',
            D: 'Navigation was learned from guides. A saddle carries cargo.'
          }
        },
        {
          id: 'q031', target: 'F4', skill: 'causation',
          stem: 'According to the passage, what did a lateen sail let a dhow do?',
          choices: {
            A: 'Make ground across the wind, rather than running only before it.',
            B: 'Carry a far larger cargo without adding to the vessel’s draft.',
            C: 'Sail straight through the monsoon reversal instead of waiting.',
            D: 'Travel through the night on a steady course with no helmsman.'
          },
          key: 'A',
          why: {
            A: 'Correct. A square sail is efficient with the wind behind it. A lateen rig lets a ship work at an angle to the wind, which turns a one-season route into a workable one.',
            B: 'Cargo capacity comes from the hull, not the rig.',
            C: 'The reversal still had to be waited out, which is why merchants overwintered in ports.',
            D: 'Every one of these vessels was steered by hand.'
          }
        },
        {
          id: 'q032', target: 'F4', skill: 'contextualization',
          stem: 'The passage names four networks. Which one does it describe as tying Europe, North Africa and Southwest Asia into a single basin?',
          choices: {
            A: 'The Mediterranean sea lanes.',
            B: 'The Indian Ocean sea lanes.',
            C: 'The trans-Saharan caravans.',
            D: 'The Eurasian Silk Roads.'
          },
          key: 'A',
          why: {
            A: 'Correct. A basin is an enclosed sea with land around it, and the Mediterranean is the one that touches all three of those regions.',
            B: 'The Indian Ocean links East Africa, Arabia, South Asia, Southeast Asia and China.',
            C: 'The trans-Saharan routes run north and south across the desert.',
            D: 'The Silk Roads run overland across Asia.'
          }
        },
        {
          id: 'q033', target: 'F4', skill: 'argumentation',
          stem: 'The passage closes by listing crops, techniques, beliefs, people and disease. What is the historical point of ending on that list?',
          choices: {
            A: 'The routes reshaped the societies they touched, well past the goods being sold.',
            B: 'The routes carried more cargo by weight than any single luxury good managed.',
            C: 'The routes were dangerous, which is why so few merchants ever completed one.',
            D: 'The routes were controlled by states, which taxed everything moving on them.'
          },
          key: 'A',
          why: {
            A: 'Correct. This is the move from trade as economics to trade as history. A route that carries a religion or a pathogen changes a society that never bought anything.',
            B: 'The passage makes no claim about tonnage.',
            C: 'Relay trade meant few merchants needed to complete a whole route, which is a different point.',
            D: 'States did tax trade, but that is not what this list is about.'
          }
        }
      ]
    },

    // ── SET J ────────────────────────────────────────────────────────────────
    {
      id: 'J',
      title: 'Who Counted, and What It Cost',
      instruction: 'Read the passage, then answer the questions in this set.',
      provenance: WRITTEN_FOR_EXAM,
      passage:
        '<p>Every classical state drew a line around who counted. Athens gave a political voice to adult male citizens and withheld it from women, from enslaved people, and from resident foreigners, who together made up most of the population. Rome widened citizenship outward across centuries and still ran on enslaved labor: the revolt led by Spartacus in 73 BCE was put down, and its survivors were crucified along a road. In Han China the Yellow Turban rebellion of 184 CE drew on peasants who had lost their land.</p>' +
        '<p>States keep records of their own order. Resistance is often the clearest evidence of what that order cost.</p>',
      items: [
        {
          id: 'q034', target: 'F3', skill: 'sourcing',
          stem: 'What does the passage identify as the most useful thing about studying revolts?',
          choices: {
            A: 'They show the costs of an order that official records present as settled.',
            B: 'They show that classical states were unstable and collapsed fairly quickly.',
            C: 'They show that enslaved people were the largest group in these societies.',
            D: 'They show the beliefs of ordinary people more accurately than other sources.'
          },
          key: 'A',
          why: {
            A: 'Correct. A state’s own records describe the order it wants. A revolt is evidence about the people that order was built on.',
            B: 'Han China and Rome both lasted centuries, and both suppressed these revolts.',
            C: 'Proportions varied a great deal by place and period.',
            D: 'Revolts are usually recorded by the people who put them down, so this overstates the case.'
          }
        },
        {
          id: 'q035', target: 'F3', skill: 'contextualization',
          stem: 'Athenian democracy is often described as direct participation. What does the passage add that a student has to keep in view?',
          choices: {
            A: 'Participation was direct for citizens, and citizens were a minority of those in Athens.',
            B: 'Participation was open to any resident who could pay the assembly’s yearly fee.',
            C: 'Participation was confined to economic matters, with war left to elected generals.',
            D: 'Participation was inherited, so a citizen’s vote passed to his eldest son at death.'
          },
          key: 'A',
          why: {
            A: 'Correct. Both halves are true at once, and holding them together is what it means to understand Athenian democracy historically.',
            B: 'Citizenship was a matter of birth and status rather than a fee.',
            C: 'The assembly decided on war, treaties and public expenditure.',
            D: 'Status was inherited, though a vote was exercised in person by a living citizen.'
          }
        },
        {
          id: 'q036', target: 'F3', skill: 'causation',
          stem: 'Han governments selected officials by examining candidates on Confucian texts. Which governing problem did that practice most directly address?',
          choices: {
            A: 'Staffing an administration with men whose loyalty ran to the throne, not to a family.',
            B: 'Raising the revenue needed to garrison the empire’s long and exposed northern frontier.',
            C: 'Settling which branch of the imperial family held the stronger claim to the throne.',
            D: 'Persuading the peoples on the northern frontier to take up Han cultural practices.'
          },
          key: 'A',
          why: {
            A: 'Correct. An official who owes his position to an examination owes it to the state. That is a direct answer to rule by entrenched aristocratic families.',
            B: 'Revenue came from taxation, and the examinations did not raise it.',
            C: 'Succession was decided by dynastic politics rather than by examination.',
            D: 'The examinations recruited officials from inside the empire.'
          }
        }
      ]
    },

    // ── SET K ────────────────────────────────────────────────────────────────
    {
      id: 'K',
      title: 'The World at c. 1200',
      instruction: 'Read the passage, then answer the questions in this set.',
      provenance: WRITTEN_FOR_EXAM,
      passage:
        '<p>Around c. 1200 the densest connections in the world ran across Afro-Eurasia. A bowl fired in southern China could be dug up centuries later at Kilwa, on the East African coast. The rulers of Mali taxed the gold crossing the Sahara. The Song, having lost the north in 1127, governed the productive Yangtze lands and drew a growing share of their revenue from the maritime customs houses at ports such as Quanzhou.</p>' +
        '<p>None of this reached the Americas, where the Inca, the Mexica and the Mississippian societies were building on their own.</p>',
      items: [
        {
          id: 'q037', target: 'F5', skill: 'argumentation',
          stem: 'A student claims that long-distance trade reshaped states and not only markets. Which detail in the passage gives that claim its strongest support?',
          choices: {
            A: 'The Song drew a growing share of government revenue from maritime customs houses.',
            B: 'A bowl fired in southern China was dug up centuries later at Kilwa in East Africa.',
            C: 'The densest connections anywhere in the world at this date ran across Afro-Eurasia.',
            D: 'The Inca, the Mexica and the Mississippian societies were building on their own.'
          },
          key: 'A',
          why: {
            A: 'Correct. Customs revenue is trade entering the state’s own finances, which is what makes this evidence about states rather than about markets.',
            B: 'The bowl proves goods moved a very long way, which is a claim about markets.',
            C: 'This describes the network without saying anything about states.',
            D: 'This is about a region the trade did not reach.'
          }
        },
        {
          id: 'q038', target: 'F5', skill: 'causation',
          stem: 'Which explanation best accounts for how a bowl made in southern China came to be buried at Kilwa before c. 1200?',
          choices: {
            A: 'It passed through many merchants and markets along the monsoon-driven sea lanes.',
            B: 'It was carried the whole way by one merchant sailing from China to East Africa.',
            C: 'It moved overland across Asia and then south through the Sahara toward the coast.',
            D: 'It arrived aboard the first European ships to round the southern tip of Africa.'
          },
          key: 'A',
          why: {
            A: 'Correct. This is relay trade seen from the far end. An object crosses an ocean without any single person crossing it.',
            B: 'Very few ships sailed the whole route, which is what makes the relay structure necessary.',
            C: 'The trans-Saharan routes ran north and south, not east from China.',
            D: 'European ships round the Cape roughly three centuries after this date.'
          }
        },
        {
          id: 'q039', target: 'F5', skill: 'contextualization',
          stem: 'Which statement about the Americas at c. 1200 does the passage best support?',
          choices: {
            A: 'Complex societies developed there apart from the Afro-Eurasian exchange described.',
            B: 'Complex societies there weakened because Afro-Eurasian goods never came to them.',
            C: 'Societies there stayed smaller than any of the Afro-Eurasian states named above.',
            D: 'Societies there traded with Mali, which is how gold crossed westward by sea.'
          },
          key: 'A',
          why: {
            A: 'Correct. Separate development, not lesser development. That distinction is the whole point of the sentence.',
            B: 'The passage describes them building, and gives no cause of weakening.',
            C: 'The passage makes no comparison of size, and these were large societies.',
            D: 'No such trade existed, and the gold the passage names crossed the Sahara.'
          }
        },
        {
          id: 'q040', target: 'F5', skill: 'argumentation',
          stem: 'A student writes: “The Song moved south, so their trade grew.” Which revision turns that into a historical explanation rather than a sequence?',
          choices: {
            A: 'Losing the north left the Song on the Yangtze, and sea customs replaced lost land revenue.',
            B: 'The Song moved south in 1127, and after that the trade at Quanzhou grew considerably.',
            C: 'The Song were a commercial dynasty, so growth in their overseas trade is unsurprising.',
            D: 'Trade was growing across Afro-Eurasia at this date, and the Song shared in that growth.'
          },
          key: 'A',
          why: {
            A: 'Correct. It names the mechanism: territory lost, revenue lost, and a different revenue base built to replace it. That is why the move produced the growth.',
            B: 'This puts the two events in order without saying how one produced the other.',
            C: 'This explains the outcome by asserting a character, which assumes what it should show.',
            D: 'This is context. It accounts for the region rather than for the Song in particular.'
          }
        }
      ]
    }
  ]
};
