#!/usr/bin/env node
/**
 * build-xray.js
 *
 * Inlines the X-Ray's shared code into teacher/xray.html, the same way
 * build-skills-lens.js fills the Skills Lens.
 *
 * The page is one file with a Content-Security-Policy of `default-src 'none'`, so
 * everything it runs has to be physically inside it. That makes a copy, and a copy
 * is what this repository keeps being bitten by, so the copy is generated and
 * checked: this script writes it and `--check` fails the push the moment the
 * inlined bytes drift from the sources. Never hand-edit between the sentinels.
 *
 * Five things go in:
 *   scripts/lib/xray-sections.js    the seven classes and who teaches them
 *   scripts/lib/xray-roster.js      joins the two exports into account-to-class
 *   scripts/lib/xray-core.js        the calculations, tested on their own
 *   scripts/lib/xray-demo-data.js   the invented class (demonstration build only)
 *   a prompt catalog                lifted from assets/data/skills-map.js, so no
 *                                   prompt or term is ever retyped
 *
 * Usage:
 *   node scripts/build-xray.js [--check]
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const PAGE = path.join(ROOT, 'teacher', 'xray.html');
const CHECK = process.argv.includes('--check');

const OPEN = '<!-- BEGIN INLINED LIBS, generated by scripts/build-xray.js -->';
const CLOSE = '<!-- END INLINED LIBS -->';
// Order matters: the sections file first, because the roster and the demo read it
// from a global once inlined, then the roster, the calculations, and the demo.
const LIBS = ['scripts/lib/xray-sections.js', 'scripts/lib/xray-roster.js', 'scripts/lib/xray-core.js', 'scripts/lib/xray-demo-data.js'];
const TOPICS = ['2.3'];

function catalogs() {
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(path.join(ROOT, 'assets/data/skills-map.js'), 'utf8'), sandbox);
  const map = sandbox.window.BEHISTORICAL_SKILLS_MAP;
  const X = require(path.join(ROOT, 'scripts/lib/xray-core.js'));
  const out = {};
  TOPICS.forEach(id => {
    const c = X.buildCatalog(map.topics, id);
    if (!c) throw new Error(`skills map has no topic ${id}`);
    out[id] = c;
  });
  return out;
}

function block() {
  const parts = LIBS.map(rel => {
    const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    if (/<\/script/i.test(src)) throw new Error(`${rel} contains a </script sequence, which cannot be inlined verbatim`);
    return `<script>\n/* ${rel}\n   Generated copy. Edit the source and run: node scripts/build-xray.js */\n${src}</script>`;
  });
  // "<" is escaped so no string in the data can end the script element early.
  const json = JSON.stringify(catalogs()).replace(/</g, '\\u003c');
  parts.push(`<script>\n/* prompt catalog, from assets/data/skills-map.js */\nwindow.BH_XRAY_CATALOGS = ${json};\n</script>`);
  return [OPEN].concat(parts).concat([CLOSE]).join('\n');
}

function main() {
  const html = fs.readFileSync(PAGE, 'utf8');
  const wanted = block();
  const start = html.indexOf(OPEN);
  const end = html.indexOf(CLOSE);
  if (start === -1 || end === -1) {
    console.error('teacher/xray.html has no inline-libs sentinels.');
    process.exit(2);
  }
  const current = html.slice(start, end + CLOSE.length);
  if (current === wanted) { console.log('  teacher/xray.html is up to date.'); return; }
  if (CHECK) {
    console.error('  teacher/xray.html is STALE: its inlined code no longer matches the sources.');
    console.error('  Run: node scripts/build-xray.js');
    process.exit(1);
  }
  fs.writeFileSync(PAGE, html.slice(0, start) + wanted + html.slice(end + CLOSE.length), 'utf8');
  console.log('  Inlined ' + LIBS.length + ' libraries and the prompt catalog into teacher/xray.html');
}

if (require.main === module) main();
module.exports = { OPEN, CLOSE, LIBS, TOPICS, block };
