#!/usr/bin/env node
'use strict';

/* Mechanical guardrails for the data-driven Teaching OS.
 * The point is to stop future topics from copying topic-specific versions of
 * the cockpit or hand-maintaining a student deck that can drift from teacher data.
 */

const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const read = rel => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const exists = rel => fs.existsSync(path.join(ROOT, rel));

let failed = 0;
function check(name, pass, detail = '') {
  console.log(`  ${pass ? 'PASS' : 'FAIL'}  ${name}${detail ? `  (${detail})` : ''}`);
  if (!pass) failed++;
}

console.log('\nTeaching OS architecture contract\n');

const shared = 'teacher/teaching-os-shared.js';
check('shared cockpit module exists', exists(shared));
if (exists(shared)) {
  const src = read(shared);
  check('shared cockpit owns the Run of Show toggle', src.includes("id='runOfShowToggle'") || src.includes("id=\"runOfShowToggle\"") || src.includes("btn.id='runOfShowToggle'"));
  check('shared cockpit owns teacher layout CSS', src.includes('.cockpit') && src.includes('.intel-scroll') && src.includes('.timeline'));
}

const { DECKS } = require('../build-teaching-os-student-decks.js');
const teachingKeys = DECKS.map(deck => deck.key.replace('.', '-'));

for (const key of teachingKeys) {
  const wrapper = `teacher/data/topic-${key}-teaching.js`;
  const data = `teacher/data/topic-${key}-presentation-assets.js`;
  const visual = `teacher/data/topic-${key}-visual-assets.js`;
  const student = `assets/data/presentations/topic-${key}-student.js`;

  console.log(`\n  Topic ${key.replace('-', '.')}\n`);
  check(`${key} teaching wrapper exists`, exists(wrapper));
  check(`${key} data-only presentation asset layer exists`, exists(data));
  check(`${key} topic visual layer exists`, exists(visual));
  check(`${key} student data exists`, exists(student));

  if (exists(wrapper)) {
    const src = read(wrapper);
    check(`${key} wrapper loads the canonical base`, src.includes(`topic-${key}-teaching-base.js`));
    check(`${key} wrapper loads data-only presentation assets`, src.includes(`topic-${key}-presentation-assets.js`));
    check(`${key} wrapper loads the shared cockpit`, src.includes('teaching-os-shared.js'));
  }

  if (exists(data)) {
    const src = read(data);
    check(`${key} presentation data is DOM-free`, !/\bdocument\b|querySelector|createElement|appendChild/.test(src));
  }

  if (exists(visual)) {
    const src = read(visual);
    const duplicated = ['runOfShowToggle', '.cockpit', '.intel-scroll', '.timeline'].filter(token => src.includes(token));
    check(`${key} visual layer contains no shared cockpit implementation`, duplicated.length === 0, duplicated.join(', ') || 'topic-only');
  }

  if (exists(student)) {
    const src = read(student);
    check(`${key} student data declares itself generated`, src.startsWith('/* GENERATED by scripts/build-teaching-os-student-decks.js. Do not hand-edit. */'));
    // Guard actual teacher-coaching fields/labels, not ordinary student prose such as
    // “the story” or a historical use of “land.” The prior broad word check created
    // false positives when projected copy legitimately used those English words.
    const teacherPayload = /\bnotes\s*:|listenFor|teacher intelligence|AP CONNECTION|["'](?:land|story|ask|avoid)["']\s*:/i;
    check(`${key} student bytes contain no teacher coaching payload`, !teacherPayload.test(src));
  }
}

check('generated-artifact gate invokes Teaching OS generator', read('scripts/test/readings-reproducible.test.js').includes('scripts/build-teaching-os-student-decks.js'));

const studentDir = path.join(ROOT, 'assets/data/presentations');
const studentKeys = fs.readdirSync(studentDir)
  .map(name => /^topic-(\d+-\d+)-student\.js$/.exec(name))
  .filter(Boolean)
  .map(match => match[1])
  .sort();
check(
  'Teaching OS registry and generated student files agree in both directions',
  JSON.stringify([...teachingKeys].sort()) === JSON.stringify(studentKeys),
  `registry=${[...teachingKeys].sort().join(', ')} files=${studentKeys.join(', ')}`
);

console.log('\n  Authoring process discovery\n');
const authoringPath = 'docs/PRESENTATION-AUTHORING.md';
const architecturePath = 'docs/TEACHING-OS.md';
check('canonical presentation authoring standard exists', exists(authoringPath));
check('canonical Teaching OS implementation contract exists', exists(architecturePath));

if (exists(authoringPath)) {
  const contract = read(authoringPath);
  check(
    'authoring contract locks the final production line',
    contract.includes('CED -> existing-course constraint check -> ninth-grade story -> memorable spine -> must-have evidence -> narrative beats -> story approval gate -> retelling slide -> asset and capability inventory -> visual plan -> canonical teacher build -> generated student deck -> ecosystem and registry sync -> instructional verification -> technical verification -> adjacent findings -> ship')
  );
  check('authoring contract says slide count follows the story', contract.includes('Slide count follows the story.'));
  check('authoring contract contains no numeric slide-count target', !/\b12\s*(?:to|-)\s*16\b/.test(contract));
  check('authoring contract makes Big Rocks optional', contract.includes('Big Rocks" are an optional organizing device'));
  check('authoring contract includes the story approval gate', contract.includes('## 8. Story approval gate'));
  check('authoring contract names a retelling slide', contract.includes('## 9. Name the retelling slide'));
  check('authoring contract blocks remembered Commons filenames', contract.includes('Never write a Commons filename from memory'));
  check('authoring contract requires meaningful failure-capable checks', contract.includes('Any check used as evidence that work is complete must be shown capable of failing'));
  check('authoring contract records adjacent findings', contract.includes('## 17. Adjacent findings'));
  check('authoring contract requires independent AI peer review', contract.includes('evaluate it independently against'));
}

if (exists(architecturePath)) {
  const architecture = read(architecturePath);
  check('Teaching OS points to the authoring standard', architecture.includes('docs/PRESENTATION-AUTHORING.md'));
}

for (const entry of ['CLAUDE.md', 'AGENTS.md', '.github/copilot-instructions.md']) {
  check(`${entry} exists for AI-agent discovery`, exists(entry));
  if (exists(entry)) {
    const src = read(entry);
    check(`${entry} points agents to the authoring standard`, src.includes('docs/PRESENTATION-AUTHORING.md'));
    check(`${entry} points agents to the Teaching OS contract`, src.includes('docs/TEACHING-OS.md'));
  }
}

console.log(`\n  ${failed ? 'FAIL' : 'PASS'}  ${failed ? `${failed} architecture contract(s) failed` : 'Teaching OS architecture is centralized and drift-gated'}`);
if (failed) process.exit(1);
