#!/usr/bin/env node
'use strict';

/* Mechanical guardrails for the data-driven Teaching OS.
 * The point is to stop future topics from copying topic-specific versions of
 * the cockpit or hand-maintaining a student deck that can drift from teacher data.
 */

const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const read = rel => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const exists = rel => fs.existsSync(path.join(ROOT, rel));

let failed = 0;
function check(name, pass, detail = '') {
  console.log(`  ${pass ? 'PASS' : 'FAIL'}  ${name}${detail ? `  (${detail})` : ''}`);
  if (!pass) failed++;
}

console.log('\nTeaching OS architecture contract\n');

const shared = 'teacher/teaching-os-shared.js';
check('shared cockpit module exists', exists(shared));
if (exists(shared)) {
  const src = read(shared);
  check('shared cockpit owns the Run of Show toggle', src.includes("id='runOfShowToggle'") || src.includes("id=\"runOfShowToggle\"") || src.includes("btn.id='runOfShowToggle'"));
  check('shared cockpit owns teacher layout CSS', src.includes('.cockpit') && src.includes('.intel-scroll') && src.includes('.timeline'));
}

const { DECKS } = require('../build-teaching-os-student-decks.js');
const teachingKeys = DECKS.map(deck => deck.key.replace('.', '-'));

for (const key of teachingKeys) {
  const wrapper = `teacher/data/topic-${key}-teaching.js`;
  const data = `teacher/data/topic-${key}-presentation-assets.js`;
  const visual = `teacher/data/topic-${key}-visual-assets.js`;
  const student = `assets/data/presentations/topic-${key}-student.js`;

  console.log(`\n  Topic ${key.replace('-', '.')}\n`);
  check(`${key} teaching wrapper exists`, exists(wrapper));
  check(`${key} data-only presentation asset layer exists`, exists(data));
  check(`${key} topic visual layer exists`, exists(visual));
  check(`${key} student data exists`, exists(student));

  if (exists(wrapper)) {
    const src = read(wrapper);
    check(`${key} wrapper loads the canonical base`, src.includes(`topic-${key}-teaching-base.js`));
    check(`${key} wrapper loads data-only presentation assets`, src.includes(`topic-${key}-presentation-assets.js`));
    check(`${key} wrapper loads the shared cockpit`, src.includes('teaching-os-shared.js'));
  }

  if (exists(data)) {
    const src = read(data);
    check(`${key} presentation data is DOM-free`, !/\bdocument\b|querySelector|createElement|appendChild/.test(src));
  }

  if (exists(visual)) {
    const src = read(visual);
    const duplicated = ['runOfShowToggle', '.cockpit', '.intel-scroll', '.timeline'].filter(token => src.includes(token));
    check(`${key} visual layer contains no shared cockpit implementation`, duplicated.length === 0, duplicated.join(', ') || 'topic-only');
  }

  if (exists(student)) {
    const src = read(student);
    check(`${key} student data declares itself generated`, src.startsWith('/* GENERATED by scripts/build-teaching-os-student-decks.js. Do not hand-edit. */'));
    // Guard actual teacher-coaching fields/labels, not ordinary student prose such as
    // “the story” or a historical use of “land.” The prior broad word check created
    // false positives when projected copy legitimately used those English words.
    const teacherPayload = /\bnotes\s*:|listenFor|teacher intelligence|AP CONNECTION|["'](?:land|story|ask|avoid)["']\s*:/i;
    check(`${key} student bytes contain no teacher coaching payload`, !teacherPayload.test(src));
  }
}

check('generated-artifact gate invokes Teaching OS generator', read('scripts/test/readings-reproducible.test.js').includes('scripts/build-teaching-os-student-decks.js'));

const studentDir = path.join(ROOT, 'assets/data/presentations');
const studentKeys = fs.readdirSync(studentDir)
  .map(name => /^topic-(\d+-\d+)-student\.js$/.exec(name))
  .filter(Boolean)
  .map(match => match[1])
  .sort();
check(
  'Teaching OS registry and generated student files agree in both directions',
  JSON.stringify([...teachingKeys].sort()) === JSON.stringify(studentKeys),
  `registry=${[...teachingKeys].sort().join(', ')} files=${studentKeys.join(', ')}`
);

// DECKS alone cannot answer "is every teacher deck on the pipeline", because a
// deck that was never added to it is invisible to every check above. Topic 2.3
// shipped that way: its own teacher page, a "student" link that redirected to
// the teacher bytes, and a green gate. So membership is read off the disk.
console.log('\n  Every teacher deck on disk is on the pipeline\n');
const { NOT_YET_MIGRATED = [] } = require('../build-teaching-os-student-decks.js');
const pendingKeys = NOT_YET_MIGRATED.map(p => p.key.replace('.', '-'));
const onDisk = [...new Set(fs.readdirSync(path.join(ROOT, 'teacher'))
  .map(name => /^topic-(\d+-\d+)-(?:story-)?os\.html$/.exec(name))
  .filter(Boolean)
  .map(match => match[1]))].sort();
for (const key of onDisk) {
  const inDecks = teachingKeys.includes(key);
  const pending = pendingKeys.includes(key);
  check(`teacher/topic-${key}-os.html is in DECKS or declared not yet migrated`, inDecks || pending,
    inDecks ? 'DECKS' : pending ? 'NOT_YET_MIGRATED' : 'in neither list');
}
for (const p of NOT_YET_MIGRATED) {
  const key = p.key.replace('.', '-');
  check(`${p.key} not-yet-migrated entry still has a teacher deck and a reason`, onDisk.includes(key) && String(p.reason || '').length > 20);
  check(`${p.key} is not listed as both migrated and not yet migrated`, !teachingKeys.includes(key));
}

// A student link must never land on the teacher surface. A redirect is the
// easy way to do it by accident: the student page is tiny and harmless, and
// the page it forwards to carries every coaching note.
const unitDirs = fs.readdirSync(ROOT).filter(d => /^unit-\d+$/.test(d));
const redirectsToTeacher = [];
for (const dir of unitDirs) {
  for (const name of fs.readdirSync(path.join(ROOT, dir)).filter(n => n.endsWith('.html'))) {
    const src = read(`${dir}/${name}`);
    if (/location\.(?:replace|href)\s*\(?\s*['"][^'"]*teacher\//.test(src) || /http-equiv=["']refresh["'][^>]*teacher\//i.test(src)) {
      redirectsToTeacher.push(`${dir}/${name}`);
    }
  }
}
check('no student-facing page redirects into teacher/', redirectsToTeacher.length === 0, redirectsToTeacher.join(', ') || 'none');

// Each deck's lesson must reach its generated student copy through
// classPresentation, the one field the renderer reads.
for (const deck of DECKS) {
  const key = deck.key.replace('.', '-');
  const expected = `presentation-topic-${key}-student.html`;
  const unit = `unit-${deck.key.split('.')[0]}`;
  const shell = `${unit}/${expected}`;
  check(`${deck.key} student shell exists`, exists(shell));
  if (exists(shell)) check(`${deck.key} student shell loads its own generated data`, read(shell).includes(`presentations/topic-${key}-student.js`));
  const dataFiles = fs.readdirSync(path.join(ROOT, 'assets/data')).filter(n => n.startsWith(`lesson-${key}-`) && n.endsWith('.js'));
  const declares = dataFiles.filter(n => /classPresentation\s*[:=]/.test(read(`assets/data/${n}`)));
  const points = declares.some(n => read(`assets/data/${n}`).includes(`url: '${expected}'`));
  check(`${deck.key} lesson declares classPresentation pointing at ${expected}`, points, declares.join(', ') || 'no classPresentation');
}

// The authoring standard requires Teacher Preflight, BeReady, and a named
// retelling slide, and lets a deck omit one only if its source says why.
console.log('\n  Required instructional functions\n');
const vm = require('vm');
for (const deck of DECKS) {
  const sandbox = { window: {}, console, encodeURIComponent, decodeURIComponent };
  vm.createContext(sandbox);
  for (const rel of deck.sources) vm.runInContext(read(rel), sandbox, { filename: rel });
  const T = sandbox.window.BEHISTORICAL_TEACHING;
  const omits = (T.meta && T.meta.omits) || {};
  const explained = fn => typeof omits[fn] === 'string' && omits[fn].trim().length > 20;
  const has = {
    preflight: T.slides.some(s => s.phase === 'preflight'),
    beready: T.slides.some(s => s.phase === 'beready'),
    retelling: T.slides.filter(s => s.retelling === true && s.phase !== 'preflight').length === 1
  };
  for (const fn of ['preflight', 'beready', 'retelling']) {
    check(`${deck.key} has ${fn} or explains its omission`, has[fn] || explained(fn),
      has[fn] ? 'present' : explained(fn) ? `omitted: ${omits[fn].slice(0, 60)}...` : 'missing, with no reason in meta.omits');
    if (has[fn] && omits[fn]) check(`${deck.key} does not both carry and omit ${fn}`, false);
  }
  if (has.beready) {
    const i = T.slides.findIndex(s => s.phase === 'beready');
    check(`${deck.key} BeReady is the first student-facing slide`, T.slides.slice(0, i).every(s => s.phase === 'preflight'), `slide ${i}`);
  }
}

console.log('\n  Authoring process discovery\n');
const authoringPath = 'docs/PRESENTATION-AUTHORING.md';
const architecturePath = 'docs/TEACHING-OS.md';
check('canonical presentation authoring standard exists', exists(authoringPath));
check('canonical Teaching OS implementation contract exists', exists(architecturePath));

if (exists(authoringPath)) {
  const contract = read(authoringPath);
  check(
    'authoring contract locks the final production line',
    contract.includes('CED -> existing-course constraint check -> ninth-grade story -> memorable spine -> must-have evidence -> narrative beats -> story approval gate -> retelling slide -> asset and capability inventory -> visual plan -> canonical teacher build -> generated student deck -> ecosystem and registry sync -> instructional verification -> technical verification -> adjacent findings -> ship')
  );
  check('authoring contract says slide count follows the story', contract.includes('Slide count follows the story.'));
  check('authoring contract contains no numeric slide-count target', !/\b12\s*(?:to|-)\s*16\b/.test(contract));
  check('authoring contract makes Big Rocks optional', contract.includes('Big Rocks" are an optional organizing device'));
  check('authoring contract includes the story approval gate', contract.includes('## 8. Story approval gate'));
  check('authoring contract names a retelling slide', contract.includes('## 9. Name the retelling slide'));
  check('authoring contract blocks remembered Commons filenames', contract.includes('Never write a Commons filename from memory'));
  check('authoring contract requires meaningful failure-capable checks', contract.includes('Any check used as evidence that work is complete must be shown capable of failing'));
  check('authoring contract records adjacent findings', contract.includes('## 17. Adjacent findings'));
  check('authoring contract requires independent AI peer review', contract.includes('evaluate it independently against'));
}

if (exists(architecturePath)) {
  const architecture = read(architecturePath);
  check('Teaching OS points to the authoring standard', architecture.includes('docs/PRESENTATION-AUTHORING.md'));
}

for (const entry of ['CLAUDE.md', 'AGENTS.md', '.github/copilot-instructions.md']) {
  check(`${entry} exists for AI-agent discovery`, exists(entry));
  if (exists(entry)) {
    const src = read(entry);
    check(`${entry} points agents to the authoring standard`, src.includes('docs/PRESENTATION-AUTHORING.md'));
    check(`${entry} points agents to the Teaching OS contract`, src.includes('docs/TEACHING-OS.md'));
  }
}

console.log(`\n  ${failed ? 'FAIL' : 'PASS'}  ${failed ? `${failed} architecture contract(s) failed` : 'Teaching OS architecture is centralized and drift-gated'}`);
if (failed) process.exit(1);
