#!/usr/bin/env node
'use strict';

/* Mechanical guardrails for the data-driven Teaching OS.
 * The point is to stop future topics from copying topic-specific versions of
 * the cockpit or hand-maintaining a student deck that can drift from teacher data.
 */

const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const read = rel => fs.readFileSync(path.join(ROOT, rel), 'utf8');
const exists = rel => fs.existsSync(path.join(ROOT, rel));

let failed = 0;
function check(name, pass, detail = '') {
  console.log(`  ${pass ? 'PASS' : 'FAIL'}  ${name}${detail ? `  (${detail})` : ''}`);
  if (!pass) failed++;
}

console.log('\nTeaching OS architecture contract\n');

const shared = 'teacher/teaching-os-shared.js';
check('shared cockpit module exists', exists(shared));
if (exists(shared)) {
  const src = read(shared);
  check('shared cockpit owns the Run of Show toggle', src.includes("id='runOfShowToggle'") || src.includes("id=\"runOfShowToggle\"") || src.includes("btn.id='runOfShowToggle'"));
  check('shared cockpit owns teacher layout CSS', src.includes('.cockpit') && src.includes('.intel-scroll') && src.includes('.timeline'));
}

for (const key of ['2-1', '2-2']) {
  const wrapper = `teacher/data/topic-${key}-teaching.js`;
  const data = `teacher/data/topic-${key}-presentation-assets.js`;
  const visual = `teacher/data/topic-${key}-visual-assets.js`;
  const student = `assets/data/presentations/topic-${key}-student.js`;

  console.log(`\n  Topic ${key.replace('-', '.')}\n`);
  check(`${key} teaching wrapper exists`, exists(wrapper));
  check(`${key} data-only presentation asset layer exists`, exists(data));
  check(`${key} topic visual layer exists`, exists(visual));
  check(`${key} student data exists`, exists(student));

  if (exists(wrapper)) {
    const src = read(wrapper);
    check(`${key} wrapper loads the canonical base`, src.includes(`topic-${key}-teaching-base.js`));
    check(`${key} wrapper loads data-only presentation assets`, src.includes(`topic-${key}-presentation-assets.js`));
    check(`${key} wrapper loads the shared cockpit`, src.includes('teaching-os-shared.js'));
  }

  if (exists(data)) {
    const src = read(data);
    check(`${key} presentation data is DOM-free`, !/\bdocument\b|querySelector|createElement|appendChild/.test(src));
  }

  if (exists(visual)) {
    const src = read(visual);
    const duplicated = ['runOfShowToggle', '.cockpit', '.intel-scroll', '.timeline'].filter(token => src.includes(token));
    check(`${key} visual layer contains no shared cockpit implementation`, duplicated.length === 0, duplicated.join(', ') || 'topic-only');
  }

  if (exists(student)) {
    const src = read(student);
    check(`${key} student data declares itself generated`, src.startsWith('/* GENERATED by scripts/build-teaching-os-student-decks.js. Do not hand-edit. */'));
    // Guard actual teacher-coaching fields/labels, not ordinary student prose such as
    // “the story” or a historical use of “land.” The prior broad word check created
    // false positives when projected copy legitimately used those English words.
    const teacherPayload = /\bnotes\s*:|listenFor|teacher intelligence|AP CONNECTION|["'](?:land|story|ask|avoid)["']\s*:/i;
    check(`${key} student bytes contain no teacher coaching payload`, !teacherPayload.test(src));
  }
}

const build = read('scripts/build-teaching-os-student-decks.js');
check('Teaching OS generator declares Topic 2.1', build.includes("key: '2.1'"));
check('Teaching OS generator declares Topic 2.2', build.includes("key: '2.2'"));
check('generated-artifact gate invokes Teaching OS generator', read('scripts/test/readings-reproducible.test.js').includes('scripts/build-teaching-os-student-decks.js'));

console.log(`\n  ${failed ? 'FAIL' : 'PASS'}  ${failed ? `${failed} architecture contract(s) failed` : 'Teaching OS architecture is centralized and drift-gated'}`);
if (failed) process.exit(1);
