#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
let chromium;try{({chromium}=require('playwright-core'));}catch(e){console.error('Atlas browser test needs playwright-core.');process.exit(2);}
const root=path.resolve(__dirname,'../..');
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local'),file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404).end();return;}res.setHeader('Content-Type',types[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({executablePath:process.env.PW_CHROME||chromium.executablePath(),args:['--no-sandbox']});
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
 const open=async(topic)=>{await page.goto(base+'/unit-2/network-atlas.html?topic='+topic,{waitUntil:'domcontentloaded'});await page.waitForSelector('#atlas-map path.atlas-land');};
 await open('2.3');assert.equal(await page.locator('#atlas-topic').inputValue(),'2.3');assert.equal(await page.locator('#source-section').isVisible(),false);
 await page.locator('#prediction').fill('I should plan both departure and return.');await page.locator('#reveal-map').click();assert(await page.locator('#source-section').isVisible());
 const summer=await page.locator('.atlas-wind').getAttribute('d');await page.getByRole('button',{name:'Winter winds',exact:true}).click();assert.notEqual(await page.locator('.atlas-wind').getAttribute('d'),summer,'Season must change wind direction.');
 await page.locator('#atlas-place').selectOption('2');await page.locator('#evidence-note').fill('Calicut connects eastern and western markets.');await page.locator('#keep-evidence').click();assert((await page.locator('#evidence-bank').textContent()).includes('Calicut'));
 await page.locator('#atlas-place').selectOption('0');assert.equal(await page.locator('#evidence-note').inputValue(),'','A note from another place must not be mislabeled.');await page.locator('#atlas-place').selectOption('2');assert.equal(await page.locator('#evidence-note').inputValue(),'Calicut connects eastern and western markets.');
 await page.locator('#explanation').fill('Seasonal planning works with navigation and port relationships.');await page.reload();await page.waitForSelector('#atlas-topic');assert.equal(await page.locator('#prediction').inputValue(),'I should plan both departure and return.');
 await page.evaluate(()=>localStorage.setItem('behistorical-draft-topic-2.3-map-check-response','My earlier Map Check writing.'));await page.locator('#send-to-map').click();assert((await page.locator('#submission-status').textContent()).includes('Your atlas response is in Map Check'));
 await page.goto(base+'/unit-2/lesson-2-3-indian-ocean.html',{waitUntil:'domcontentloaded'});await page.waitForSelector('#module-grid .module-card');assert.equal(await page.locator('#module-grid .module-card').count(),10);await page.evaluate(()=>openModule('map'));assert((await page.locator('#map-check-response').inputValue()).includes('My earlier Map Check writing.'));assert((await page.locator('#map-check-response').inputValue()).includes('Seasonal planning'));
 const gathered=await page.evaluate(()=>buildWorkDocument().plain);assert(gathered.includes('Initial prediction')&&gathered.includes('Selected map observations'),'Atlas writing must reach Gather All My Work.');
 for(const topic of ['2.1','2.2','2.3','2.4','2.5','2.6','2.7']){await open(topic);await page.locator('#reveal-map').click();const n=await page.locator('#view-controls button').count();for(let i=0;i<n;i++){await page.locator('#view-controls button').nth(i).click();assert(await page.locator('#place-title').textContent());assert(await page.locator('#source-text').textContent());}assert.equal(await page.locator('#atlas-topic').inputValue(),topic);}
 await open('2.7');assert((await page.locator('#evidence-bank').textContent()).includes('Calicut'));await page.locator('[value="recall"]').check();assert.equal(await page.locator('#source-section').isVisible(),false);
 for(const width of [360,768,1100]){await page.setViewportSize({width,height:1000});await page.locator('#reveal-map').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No horizontal overflow at '+width);const sizes=await page.locator('#atlas-map text').evaluateAll(els=>els.map(e=>parseFloat(getComputedStyle(e).fontSize)));assert(sizes.every(n=>n>=11),'Map labels remain readable.');if(process.argv.includes('--shots')||process.env.BH_ATLAS_SHOTS_DIR){const out=process.env.BH_ATLAS_SHOTS_DIR?path.resolve(root,process.env.BH_ATLAS_SHOTS_DIR):path.join(root,'..');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,`atlas-${width}.png`),fullPage:true});}}
 await page.emulateMedia({media:'print'});await page.evaluate(()=>dispatchEvent(new Event('beforeprint')));assert.equal(await page.locator('#submission-preview').isVisible(),true,'Print includes expanded work.');await page.emulateMedia({media:'screen'});
 const blocked=await browser.newPage();await blocked.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('blocked','SecurityError');}}));await blocked.goto(base+'/unit-2/network-atlas.html?topic=2.1');await blocked.locator('#explanation').fill('Keep me in this tab.');await blocked.locator('#atlas-topic').selectOption('2.3');await blocked.locator('#atlas-topic').selectOption('2.1');assert.equal(await blocked.locator('#explanation').inputValue(),'Keep me in this tab.');await blocked.locator('#send-to-map').click();assert((await blocked.locator('#submission-status').textContent()).includes('could not be saved'));assert.equal(await blocked.locator('#copy-fallback').inputValue().then(s=>s.includes('Keep me')),true);
 // Prove the persistence assertion can fail when the actual input-save path is removed.
 const mutant=await browser.newPage();await mutant.route('**/*',route=>{const url=route.request().url();if(!url.startsWith(base))return route.abort();if(url.endsWith('/behistorical-network-atlas.js'))return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'assets/js/behistorical-network-atlas.js'),'utf8').replace('else store.update(topic,{[el.dataset.draft]:el.value});','else void 0;')});return route.continue();});await mutant.goto(base+'/unit-2/network-atlas.html?topic=2.1');await mutant.locator('#prediction').fill('Must persist');const raw=await mutant.evaluate(()=>localStorage.getItem('behistorical-atlas-v1-topic-2.1'));assert(!raw||!raw.includes('Must persist'),'Negative control must expose lost autosave.');
 assert.deepEqual(errors,[],'No atlas or integration script errors.');await browser.close();console.log('PASS atlas browser states, monsoons, notebook, reload, Canvas gather, recall, responsive layout, print, blocked storage, and negative control.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
