#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
let chromium;try{({chromium}=require('playwright-core'));}catch(e){console.error('Atlas browser test needs playwright-core.');process.exit(2);}
const root=path.resolve(__dirname,'../..'),types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local'),file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404).end();return;}res.setHeader('Content-Type',types[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));});
let browser;
async function point(locator,fraction=.2){return locator.evaluate((el,f)=>{
 for(const step of [f,.1,.15,.25,.3,.5,.6,.7,.8,.9]){const p=el.getPointAtLength(el.getTotalLength()*step),q=new DOMPoint(p.x,p.y).matrixTransform(el.getScreenCTM());if(document.elementFromPoint(q.x,q.y)===el)return{x:q.x,y:q.y};}
 throw Error('No visible route segment outside a place target');
},fraction);}
async function routeCheck(page){const route=page.locator('.atlas-route-hit[data-route="0"]').first();await route.scrollIntoViewIfNeeded();const xy=await point(route);await page.mouse.click(xy.x,xy.y);assert.equal(await page.locator('#detail-kind').textContent(),'Connection','Direct route click must show connection information');assert.equal(await page.locator('#place-title').textContent(),'Silk Roads');}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({executablePath:process.env.PW_CHROME||chromium.executablePath(),args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1100,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const offline=p=>p.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await offline(page);
 const open=async(topic)=>{await page.goto(base+'/unit-2/network-atlas.html'+(topic?'?topic='+topic:''),{waitUntil:'domcontentloaded'});await page.waitForSelector('.atlas-place-hit');};
 await open();assert.equal(await page.locator('#atlas-topic').inputValue(),'2.7');assert.equal(await page.locator('#map-legend .map-key').count(),3);assert.equal(await page.locator('textarea').count(),0);assert.equal(await page.locator('#reveal-map').count(),0);
 await open('2.1');await routeCheck(page);await page.getByRole('button',{name:'Kashgar',exact:true}).click();assert.equal(await page.locator('#place-title').textContent(),'Kashgar');assert((await page.locator('#place-detail').textContent()).includes('caravanserai'));
 await page.getByRole('button',{name:'Samarkand',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.locator('#place-title').textContent(),'Samarkand');assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'Samarkand','Map selection preserves keyboard focus');
 await page.locator('#atlas-place').selectOption('3');assert.equal(await page.locator('#place-title').textContent(),'Tabriz');
 await open('2.3');const summer=await page.locator('.atlas-wind').getAttribute('d');await page.getByRole('button',{name:'Winter winds',exact:true}).click();assert.notEqual(await page.locator('.atlas-wind').getAttribute('d'),summer);await page.locator('#map-legend').getByRole('button',{name:'Arabian Sea seasonal winds'}).click();assert.equal(await page.locator('#place-title').textContent(),'Winter monsoon');
 for(const topic of ['2.1','2.2','2.3','2.4','2.5','2.6','2.7']){await open(topic);const n=await page.locator('#view-controls button').count();for(let i=0;i<n;i++){await page.locator('#view-controls button').nth(i).click();await page.locator('#atlas-place').selectOption('0');assert(await page.locator('#place-detail').textContent());assert(await page.locator('#source-text').textContent());}}
 await page.evaluate(()=>{localStorage.setItem('behistorical-atlas-v1-topic-2.1','{"prediction":"Original atlas writing"}');localStorage.setItem('behistorical-draft-topic-2.1-map-check-response','Original Map Check');});await open('2.1');await routeCheck(page);assert.equal(await page.evaluate(()=>localStorage.getItem('behistorical-draft-topic-2.1-map-check-response')),'Original Map Check');assert((await page.evaluate(()=>localStorage.getItem('behistorical-atlas-v1-topic-2.1'))).includes('Original atlas writing'));
 await page.goto(base+'/unit-2/lesson-2-1-silk-roads.html',{waitUntil:'domcontentloaded'});await page.waitForSelector('#module-grid .module-card');assert.equal(await page.locator('#module-grid .module-card').count(),10);await page.evaluate(()=>openModule('map'));assert.equal(await page.locator('#map-check-response').inputValue(),'Original Map Check');assert.equal(await page.locator('#pop-body a[href*="network-atlas"]').count(),0,'No atlas assignment in Map Check');
 await page.goto(base+'/unit-2/index.html',{waitUntil:'domcontentloaded'});const frame=page.frameLocator('#unit2-atlas-frame');await page.locator('#unit2-atlas-frame').scrollIntoViewIfNeeded();await frame.locator('.atlas-place-hit').first().waitFor();assert.equal(await frame.locator('#atlas-topic').inputValue(),'2.7');
 await frame.getByText('Historical source and map context',{exact:true}).click();await page.waitForFunction(()=>{const f=document.getElementById('unit2-atlas-frame');return f.clientHeight>=f.contentDocument.getElementById('network-atlas').getBoundingClientRect().height;});await frame.getByText('Historical source and map context',{exact:true}).click();
 const resize=await page.evaluate(()=>{const f=document.getElementById('unit2-atlas-frame'),before=f.style.height;dispatchEvent(new MessageEvent('message',{origin:location.origin,data:{type:'BH_ATLAS_HEIGHT',height:9000},source:window}));return{before,after:f.style.height};});assert.equal(resize.after,resize.before,'Untrusted resize sender must be ignored');
 for(const width of [360,768,1100]){await page.setViewportSize({width,height:1000});await frame.locator('#atlas-topic').selectOption('2.3');await frame.locator('#atlas-place').selectOption('4');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Hub does not overflow');assert.equal(await frame.locator('body').evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Graphic does not overflow');if(process.argv.includes('--shots')||process.env.BH_ATLAS_SHOTS_DIR){const out=process.env.BH_ATLAS_SHOTS_DIR?path.resolve(root,process.env.BH_ATLAS_SHOTS_DIR):path.join(root,'..');fs.mkdirSync(out,{recursive:true});await page.locator('#network-atlas').screenshot({path:path.join(out,`atlas-${width}.png`)});}}
 const touch=await browser.newPage({viewport:{width:360,height:844},hasTouch:true,isMobile:true});await offline(touch);await touch.goto(base+'/unit-2/network-atlas.html?topic=2.3');
 for(const name of ['Quanzhou','Calicut','Gujarat region']){const marker=touch.getByRole('button',{name,exact:true});await marker.scrollIntoViewIfNeeded();const box=await marker.boundingBox();await touch.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);assert.equal(await touch.locator('#place-title').textContent(),name,'Touch selects the nearest place, including overlapping targets');}
 await touch.locator('#atlas-topic').selectOption('2.1');const touchRoute=touch.locator('.atlas-route-hit[data-route="0"]').first();await touchRoute.scrollIntoViewIfNeeded();const tapPoint=await point(touchRoute,.4);await touch.touchscreen.tap(tapPoint.x,tapPoint.y);assert.equal(await touch.locator('#detail-kind').textContent(),'Connection','Touch selects a route away from a place marker');
 const blocked=await browser.newPage();await offline(blocked);await blocked.addInitScript(()=>{for(const name of ['localStorage','sessionStorage'])Object.defineProperty(window,name,{get(){throw Error('Storage blocked');}});});await blocked.goto(base+'/unit-2/network-atlas.html?topic=2.1');await routeCheck(blocked);
 const mutant=await browser.newPage();await mutant.route('**/*',r=>{const url=r.request().url();if(!url.startsWith(base))return r.abort();if(url.endsWith('/behistorical-network-atlas.js'))return r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(root,'assets/js/behistorical-network-atlas.js'),'utf8').replace(".on('click',fn)",".on('click',()=>{})")});return r.continue();});await mutant.goto(base+'/unit-2/network-atlas.html?topic=2.1');await assert.rejects(()=>routeCheck(mutant),/Direct route click/,'Removed map handler must fail the real click assertion');
 assert.deepEqual(errors,[]);console.log('PASS immediate visual, real route/location clicks, keyboard, touch, views, hub embed, responsive layout, retained data, blocked storage, and removed-handler negative control.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
